channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - cudf=23.06
  - dask-cudf=23.06
  - dask-cuda=23.06
  - dash
  - jupyterlab
  - jupyter-dash
  - jupyterlab-dash
  - dash-html-components
  - dash-core-components
  - dash-daq
  - dash-bootstrap-components
  - datashader>=0.15
  - pyproj
  - bokeh
